# inpackage: True
with-expecter: True
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName | snakecase}}_mock.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
# dir: "{{.InterfaceDir}}"
packages:
  cloud.google.com/go/cloudtasks/apiv2/cloudtaskspb:
    config:
      dir: "test/mocks/googleapis/cloudtaskspb"
    interfaces:
      CloudTasksServer:
