dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
pkgname: "{{.SrcPackageName}}_mocks"
template: testify
filename: "{{.InterfaceName | snakecase}}_mock.go"
packages:
  cloud.google.com/go/cloudtasks/apiv2/cloudtaskspb:
    config:
      dir: test/mocks/googleapis/cloudtaskspb
    interfaces:
      CloudTasksServer: {}
