name: Test

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test-unit
